<?php
/**
 * Created by PhpStorm.
 * User: Bac Truong Van
 * Date: 04/03/2017
 * Time: 6:00 CH
 */
namespace frontend\components;

use Yii;
use yii\base\Widget;

class WidgetBase extends Widget
{
    public $dir;
    public $view;
    public function init()
    {
        $class = (new \ReflectionClass($this))->getShortName();
        $this->dir = strtolower(substr($class, 0, -6));
        parent::init(); // TODO: Change the autogenerated stub
    }
}